sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t northersky/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true northersky/docker-react-test yarn test